---
# tasks file for database
- name: Install PostgreSQL
  package: name=postgresql state=latest

- name: Setup postgresql access configuration
  template: src=pg_hba.conf dest=/etc/postgresql/9.4/main mode='0640'
  notify: Restart PostgreSQL

- name: Install the package python-psycopg2 to manage postgres from ansible modules
  apt: name=python-psycopg2 state=present

- name: Create postgres user [registry]
  postgresql_user: name="{{ dbuser }}" password="{{ dbpassword }}" login_host=localhost login_user=postgres role_attr_flags=CREATEDB

- name: Create postgres database [registry]
  postgresql_db: name=registry login_host=localhost login_user="{{ dbuser }}" owner="{{ dbuser }}"
