---
# tasks file for tomcat
- name: Create tomcat user
  user: name=tomcat createhome=no shell=/bin/false system=yes

- name: Extract Apache Tomcat
  unarchive:
    src: "{{ tomcat_base }}.tar.gz"
    dest: /opt/
    owner: tomcat
    group: tomcat
    creates: /opt/{{ tomcat_base }}

- name: Fix Tomcat directory ownership
  file:
    path: /opt/{{ tomcat_base }}
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes

- name: Create Tomcat link
  file:
    src: /opt/{{ tomcat_base }}
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    state: link

- name: Install postgres JDBC driver
  copy: src="{{ jdbc_filename }}" dest=/opt/tomcat/lib

- name: Install tomcat-users.xml
  template: src=tomcat-users.xml dest=/opt/tomcat/conf

- name: Install server.xml
  template: src=server.xml dest=/opt/tomcat/conf

- name: Install systemd unit file
  template: src=tomcat.service dest=/etc/systemd/system/tomcat.service

- name: Install systemd service
  systemd: daemon_reload=yes name=tomcat enabled=yes state=started
